import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import WspButton from "./components/WspButton.jsx"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JVH Portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="w-100 overflow-x-hidden" lang="en">
      <Navbar />
      <body className= {` ${inter.className}`}>
      {children}
      <WspButton />
      </body>
    </html>
  );
}
